(write (setf my-array (make-array '(10))))
(terpri)
(setf (aref my-array 0) 25)
(setf (aref my-array 1) 23)
(setf (aref my-array 2) 11)
(setf (aref my-array 3) 22)
(setf (aref my-array 4) 33)
(setf (aref my-array 5) 44)
(setf (aref my-array 6) 55)
(setf (aref my-array 7) 66)
(setf (aref my-array 8) 77)
(setf (aref my-array 9) 88)
(write my-array)
