(with-input-from-string (stream "Welcome to lisp")
  (print (read-char stream))
  (print (read-char stream))
  (print (read-char stream))
  (print (read-char stream))
  (print (read-char stream))
  (print (read-char stream))
  (print (read-char stream))
  (print (read-char stream))
  (print (read-char stream))
  (print (read-char stream))
  (print (read-char stream))
)
